# Generated by Codex on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmenu', '0003_remove_menu_unique_menu_item_per_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuconfig',
            name='currency',
            field=models.CharField(default='MWK', max_length=10),
        ),
    ]
