# Generated by Codex on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmenu', '0004_menuconfig_currency_default_mwk'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
