# Generated by Django 6.0 on 2026-08-19 23:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmenu', '0005_menu_is_visible'),
        ('inventory', '0031_inventoryitem_reserved_stock_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOptionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('group_type', models.CharField(choices=[('option', 'Option'), ('side', 'Side'), ('addon', 'Add-on')], default='option', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('min_select', models.PositiveIntegerField(default=0)),
                ('max_select', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='digitalmenu.menu')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('price_mode', models.CharField(choices=[('delta', 'Add to base price'), ('override', 'Override base price')], default='delta', max_length=20)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('recipe', models.JSONField(blank=True, default=list)),
                ('linked_inventory_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('is_default', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_inventory_item', models.ForeignKey(blank=True, help_text='Optional stock item to consume directly when this option is selected.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_options', to='inventory.inventoryitem')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='digitalmenu.menuoptiongroup')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='menuoptiongroup',
            index=models.Index(fields=['menu', 'is_visible'], name='digitalmenu_menu_id_d11ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='menuoptiongroup',
            index=models.Index(fields=['group_type'], name='digitalmenu_group_t_a9ff87_idx'),
        ),
        migrations.AddIndex(
            model_name='menuoption',
            index=models.Index(fields=['group', 'is_visible'], name='digitalmenu_group_i_036a46_idx'),
        ),
        migrations.AddIndex(
            model_name='menuoption',
            index=models.Index(fields=['linked_inventory_item'], name='digitalmenu_linked__ddd154_idx'),
        ),
    ]
