# Generated by Django 6.0 on 2026-08-25 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmenu', '0008_inventory_products_for_prepared_menu'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='menu',
            new_name='digitalmenu_branch__7b6529_idx',
            old_name='digitalmenu_branch__2ace7e_idx',
        ),
    ]
