# Generated by Django 6.0 on 2026-09-13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0034_businesssettings_customer_bill_payment_accounts'),
        ('take_orders', '0013_takeorder_kitchen_ticket_printed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('checked_in', 'Checked in'), ('in_service', 'In service'), ('ready_for_payment', 'Ready for payment'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], default='booked', max_length=32)),
                ('services', models.JSONField(default=list, help_text='Immutable snapshot of services, quantities, prices, and consumable recipes.')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='business.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='business.business')),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_checked_in', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='business.customer')),
                ('take_order', models.OneToOneField(blank=True, help_text='The normal service order created when this appointment is checked in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='take_orders.takeorder')),
            ],
            options={
                'ordering': ['scheduled_start', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['business', 'branch', 'scheduled_start'], name='appointment_busines_44f6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['branch', 'status', 'scheduled_start'], name='appointment_branch__d837a5_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['customer', 'scheduled_start'], name='appointment_custome_046536_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['take_order'], name='appointment_take_or_c95959_idx'),
        ),
    ]
