# Generated by Django 6.0 on 2026-09-14

import django.db.models.deletion
from django.db import migrations, models


def link_existing_settlements(apps, schema_editor):
    Appointment = apps.get_model('appointments', 'Appointment')
    Order = apps.get_model('pos_sessions', 'Order')

    for order in Order.objects.filter(
        payment_method='Appointment Settlement',
        is_paid=True,
    ).exclude(appointment_settlement={}):
        metadata = order.appointment_settlement
        if not isinstance(metadata, dict):
            continue
        appointment_id = str(
            metadata.get('appointment_id') or metadata.get('appointmentId') or ''
        ).strip()
        if not appointment_id:
            continue
        Appointment.objects.filter(
            pk=appointment_id,
            settled_order__isnull=True,
        ).update(settled_order_id=order.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_cancellation_reason_and_more'),
        ('pos_sessions', '0020_order_appointment_settlement_payment_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='settled_order',
            field=models.OneToOneField(
                blank=True,
                help_text='The completed POS sale that settled this appointment.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='settled_appointment',
                to='pos_sessions.order',
            ),
        ),
        migrations.RunPython(link_existing_settlements, migrations.RunPython.noop),
    ]
