# Generated by Django 5.0 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mra_eis', '0004_alter_mraconfiguration_config_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncretryqueue',
            name='operation_type',
            field=models.CharField(
                choices=[
                    ('submit_invoice', 'Submit Invoice'),
                    ('submit_pos_order', 'Submit POS Order'),
                    ('sync_offline_invoices', 'Sync Offline Invoices'),
                    ('refresh_token', 'Refresh Token'),
                    ('fetch_configuration', 'Fetch Configuration'),
                ],
                max_length=50,
            ),
        ),
    ]
