# Generated by Django 6.0 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mra_eis', '0008_encrypt_terminal_credentials_and_redact_audits'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mrainvoice',
            new_name='mra_eis_mra_termina_0de798_idx',
            old_name='mra_eis_mra_term_fisc_8dd85c_idx',
        ),
        migrations.AlterField(
            model_name='mrainvoice',
            name='invoice_number',
            field=models.BigIntegerField(
                help_text='Sequential invoice number per terminal fiscal day'
            ),
        ),
        migrations.AlterField(
            model_name='terminalauditlog',
            name='action',
            field=models.CharField(
                choices=[
                    ('activated', 'Terminal Activated'),
                    ('token_refreshed', 'Token Refreshed'),
                    ('online_status_changed', 'Online Status Changed'),
                    ('configuration_updated', 'Configuration Updated'),
                    ('mra_request_signed', 'MRA Request Signed'),
                    ('suspended', 'Terminal Suspended'),
                    ('deactivated', 'Terminal Deactivated'),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name='fiscalinvoicesequence',
            index=models.Index(
                fields=['terminal', 'julian_date'],
                name='mra_eis_fis_termina_58f345_idx',
            ),
        ),
    ]
