# Generated by Django 6.0 on 2026-08-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_sessions', '0013_order_payment_method_laybuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_options',
            field=models.JSONField(blank=True, default=list, help_text='Snapshot of selected meal options/sides, including names, prices, and stock recipes.'),
        ),
    ]
