# Generated by Django 6.0 on 2026-08-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_sessions', '0015_prepared_menu_item_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='charges_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='charges_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='Immutable snapshot of additional charges/levies applied to this order.'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='charges_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional charge/levy amount for this item', max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='charges_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='Immutable snapshot of additional charges/levies applied to this order line.'),
        ),
    ]
