# Generated by Django 6.0 on 2026-08-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_sessions', '0016_order_charges_amount_order_charges_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='total_bank_transfer_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Mobile Money', 'Mobile Money'), ('Bank Transfer', 'Bank Transfer'), ('On Account', 'On Account'), ('Laybuy', 'Laybuy'), ('Other', 'Other')], max_length=20),
        ),
    ]
