# Generated by Django 4.2.27 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_sessions', '0019_order_eis_special_sale_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='appointment_settlement',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Appointment checkout metadata used to settle recorded deposits exactly once.',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_breakdown',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Immutable payment allocation snapshot, used for appointment deposits and final settlement.',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(
                choices=[
                    ('Cash', 'Cash'),
                    ('Card', 'Card'),
                    ('Mobile Money', 'Mobile Money'),
                    ('Bank Transfer', 'Bank Transfer'),
                    ('Appointment Settlement', 'Appointment Settlement'),
                    ('On Account', 'On Account'),
                    ('Laybuy', 'Laybuy'),
                    ('Other', 'Other'),
                ],
                max_length=32,
            ),
        ),
    ]
