# Generated by Django 6.0 on 2026-09-07 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0033_businesscharge_application_rule'),
        ('hr', '0002_attendancerecord_leavetype_leaverequest_leavebalance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('clock_out__isnull', True), ('status', 'open')), fields=('employee',), name='hr_one_open_attendance_per_employee'),
        ),
    ]
