# Generated by Django 6.0 on 2026-09-07 00:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0033_businesscharge_application_rule'),
        ('hr', '0003_attendancerecord_hr_one_open_attendance_per_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('approved', 'Approved'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=20)),
                ('currency', models.CharField(default='MWK', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_runs', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='business.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_runs', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_payroll_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title_snapshot', models.CharField(blank=True, max_length=150)),
                ('pay_frequency_snapshot', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(default='MWK', max_length=3)),
                ('base_pay', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('deductions_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_entries', to='hr.employee')),
                ('employment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_entries', to='hr.employmentterm')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='hr.payrollrun')),
            ],
            options={
                'ordering': ['employee__last_name', 'employee__first_name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_monthly_hours', models.DecimalField(decimal_places=2, default=208, max_digits=7)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_settings', to='business.business')),
            ],
            options={
                'verbose_name': 'Payroll settings',
                'verbose_name_plural': 'Payroll settings',
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=20)),
                ('label', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payroll_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hr.payrollentry')),
            ],
            options={
                'ordering': ['kind', 'label'],
                'indexes': [models.Index(fields=['payroll_entry', 'kind'], name='hr_payrolll_payroll_ca7640_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['business', 'status', 'period_end'], name='hr_payrollr_busines_812948_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('business', 'period_start', 'period_end'), name='hr_unique_payroll_period_per_business'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='hr_payroll_end_not_before_start'),
        ),
        migrations.AddIndex(
            model_name='payrollentry',
            index=models.Index(fields=['payroll_run', 'employee'], name='hr_payrolle_payroll_a8c19a_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollentry',
            constraint=models.UniqueConstraint(fields=('payroll_run', 'employee'), name='hr_unique_payroll_entry_employee'),
        ),
    ]
