# Generated by Django 6.0 on 2026-08-25 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take_orders', '0009_takeorder_cancellation_reason'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='takeorder',
            new_name='take_orders_complet_559b59_idx',
            old_name='take_orders_complet_37165d_idx',
        ),
    ]
