# Generated by Django 6.0 on 2026-04-12 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_inventoryitem_portion_price'),
        ('inventory', '0028_make_mra_code_optional'),
    ]

    operations = [
    ]
