# Generated by Codex on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_inventoryitem_reserved_stock_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='show_in_custom_sales_section',
            field=models.BooleanField(default=False, help_text="Include this product in the business's internal custom sales section/report."),
        ),
    ]
