# Generated by Django 5.0 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_inventoryitem_custom_sales_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='mraproductmapping',
            name='mra_levies',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Levy metadata returned by MRA for this mapped product. Rates are not entered locally.',
            ),
        ),
    ]
