# Generated by Django 5.1.5 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_mraproductmapping_mra_levies'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='is_service',
            field=models.BooleanField(
                default=False,
                help_text=(
                    'A salon/spa service. Services are sold like products but are not '
                    'directly stock tracked; an optional recipe deducts the consumables used.'
                ),
            ),
        ),
    ]
