# Generated by Django 5.0.14 on 2026-09-22

from decimal import Decimal

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0018_clarify_subscription_feature_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='custom_credit_discount_percent',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text='Admin-only discount for credit purchases. A value above 0 overrides the normal funding-plan discount for every future credit purchase.',
                max_digits=5,
                validators=[MinValueValidator(Decimal('0')), MaxValueValidator(Decimal('99'))],
            ),
        ),
    ]
