# Generated by Codex on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_staff_feature_disable_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(
                choices=[
                    ('Admin', 'Administrator'),
                    ('Manager', 'Manager'),
                    ('Cashier', 'Cashier'),
                    ('Waiter', 'Waiter'),
                    ('Kitchen Staff', 'Kitchen Staff'),
                ],
                default='Cashier',
                max_length=20,
            ),
        ),
    ]
