# Generated by Django 6.0 on 2026-09-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0003_alter_banktransferconfig_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurepricingconfig',
            name='feature',
            field=models.CharField(choices=[('pos', 'POS System'), ('inventory', 'Inventory Management'), ('invoicing', 'Invoices & Quotations'), ('online_menu', 'Online Menu'), ('online_ordering', 'Online Ordering'), ('delivery', 'Delivery Management'), ('kitchen', 'Kitchen Display System'), ('expense_management', 'Expense Management'), ('supplier_management', 'Supplier Management'), ('purchases', 'Purchase Orders'), ('low_stock_alerts', 'Low Stock Alerts'), ('expiry_alerts', 'Expiry Alerts'), ('customer_management', 'Customer Management'), ('reports', 'Reports'), ('analytics', 'Analytics'), ('take_orders', 'Take Orders'), ('staff_management', 'Multi-User Access'), ('waste_management', 'Waste Management'), ('stock_transfers', 'Stock Transfers'), ('stock_audits', 'Stock Audits'), ('tax_management', 'Tax Management')], help_text='Feature identifier', max_length=50, unique=True),
        ),
    ]
