# Generated by Codex on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_invoice_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='custom_sales_section_name',
            field=models.CharField(blank=True, default='', help_text='Internal section label, for example Bar, Drinks, or Beer Counter.', max_length=80),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='enable_custom_sales_section',
            field=models.BooleanField(default=False, help_text='Enable an internal product section for separate reporting and workflow views.'),
        ),
    ]
