# Generated by Django 6.0 on 2026-08-25 02:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_custom_sales_section_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('charge_type', models.CharField(choices=[('LEVY', 'Levy'), ('SERVICE_CHARGE', 'Service Charge'), ('OTHER', 'Other Charge')], default='LEVY', max_length=30)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calculation_method', models.CharField(choices=[('exclusive', 'Add on top of sale'), ('inclusive', 'Included in sale price')], default='exclusive', max_length=20)),
                ('calculation_base', models.CharField(choices=[('net_subtotal', 'Net subtotal before VAT'), ('gross_total', 'Gross total after VAT')], default='net_subtotal', max_length=20)),
                ('auto_apply', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_dirty', models.BooleanField(default=True, help_text='Marks record as dirty (needs syncing). Set to False after successful sync.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='businesscharge',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='business.business'),
        ),
        migrations.AddField(
            model_name='businesscharge',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='businesscharge',
            index=models.Index(fields=['business', 'is_active'], name='business_bu_busines_279651_idx'),
        ),
        migrations.AddIndex(
            model_name='businesscharge',
            index=models.Index(fields=['charge_type'], name='business_bu_charge__6b5744_idx'),
        ),
        migrations.AddIndex(
            model_name='businesscharge',
            index=models.Index(fields=['is_dirty'], name='business_bu_is_dirt_05de8c_idx'),
        ),
    ]
