# Generated by Django 6.0 on 2026-08-25 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0029_businesscharge_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoice',
            new_name='business_in_busines_c8bfc2_idx',
            old_name='business_in_busines_b4e52c_idx',
        ),
    ]
