# Generated by Django 6.0 on 2026-09-05

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0032_customer_account_payment_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscharge',
            name='application_rule',
            field=models.CharField(
                choices=[
                    ('all_sales', 'Every sale'),
                    ('over_amount', 'Only sales over an amount'),
                ],
                default='all_sales',
                help_text='Whether the charge applies to every sale or only sales over a configured amount.',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='businesscharge',
            name='minimum_sale_amount',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='The sale total after VAT must be greater than this amount when the over-amount rule is selected.',
                max_digits=12,
            ),
        ),
    ]
